# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: ">=10.0"

matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
